### ISSUE TITLE
Current config location doesn't allow modpack devs to ship default configs

### ISSUE THREAD

**Issue by tobi-polar** [JSJBDEV/VillagerMemoryTweaks#1]
Having the config file in each world save folder means I can't ship a default setting for my pack. Any chance you could move the config file to the configs folder?

**Comment by JSJBDEV** [comment]
I'm looking into why this occurs on forge. I think it is suppose to generate defaults but doesn't appear to be doing this (this is a recent forge thing I believe)

**Comment by JSJBDEV** [comment]
found a fix, will now be in the config folder when game is loaded, Ill post a release here on github and push it to CF, Thank you!

**Comment by JSJBDEV** [comment]
https://www.curseforge.com/minecraft/mc-mods/villager-memory-tweaks-vmt/files/2958530 I shall close this issue but do feel free to reopen it if it doesnt work as expected

**Comment by tobi-polar** [comment]
Thankyou! :)
