### ISSUE TITLE
MIT Without code being available

### ISSUE THREAD

**Issue by Blayyke** [JSJBDEV/VillagerMemoryTweaks#2]
Title. I noticed the mod is licensed as MIT but it doesn't appear to have any uploaded code.

**Comment by JSJBDEV** [comment]
Yeah my logic was kinda request based since a lot of my mods don't get anywhere, potentially if I release it now people can help me with the 1.16 porting, thanks for your support!

**Comment by JSJBDEV** [comment]
Do also remember that there is 2 projects here, fabric and forge and I plan on supporting both as necessary, so 1.16 would be fabric as it's already out

**Comment by JSJBDEV** [comment]
code posted for all the version I have, check the branches :D
